### ISSUE TITLE
Error: not enough values to unpack

### ISSUE THREAD

**Issue by jiezhoujenny** [SaiKrishna2604/excel-to-excel-compare#1]
Hi, thank you for your work, I tried run your code, here is the error I got:

Traceback (most recent call last):
  File "Difference.py", line 42, in <module>
    writeDiffs(df1, df2, sheet)
  File "Difference.py", line 29, in writeDiffs
    rows, cols = np.where(comparison_values == False)
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by SaiKrishna2604** [comment]
Hi, @jiezhoujenny yah the error is occurring because it is looking for an exact match like an equal number of rows in both files. So as of now, you can compare sheets with equal rows in two files. I will update the code with those complications. 
Thank You!!
